"""fix relationships

Revision ID: 5c2644b75262
Revises: 4957b35c6ea5
Create Date: 2024-08-16 10:24:44.157994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2644b75262'
down_revision = '4957b35c6ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_note_patient',
    sa.Column('doctor_note_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_note_id'], ['doctors_notes.id'], name=op.f('fk_doctor_note_patient_doctor_note_id_doctors_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients_table.id'], name=op.f('fk_doctor_note_patient_patient_id_patients_table')),
    sa.PrimaryKeyConstraint('doctor_note_id', 'patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_note_patient')
    # ### end Alembic commands ###
