"""empty message

Revision ID: 47145753da85
Revises: 504e7d97245b
Create Date: 2024-08-22 09:28:10.450092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47145753da85'
down_revision = '504e7d97245b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
