"""initial migration

Revision ID: 4957b35c6ea5
Revises: 
Create Date: 2024-08-16 10:14:24.685401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4957b35c6ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doctors_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_doctors_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart_table.id'], name=op.f('fk_patients_table_chart_id_chart_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors_table.id'], name=op.f('fk_appointments_table_doctor_id_doctors_table')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients_table.id'], name=op.f('fk_appointments_table_patient_id_patients_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors_table.id'], name=op.f('fk_doctors_notes_doctor_id_doctors_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors_notes')
    op.drop_table('appointments_table')
    op.drop_table('patients_table')
    op.drop_table('doctors_table')
    op.drop_table('users_table')
    op.drop_table('chart_table')
    # ### end Alembic commands ###
