"""empty message

Revision ID: 4ef7188670d7
Revises: 40baa6923f60
Create Date: 2024-08-19 20:42:30.167715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef7188670d7'
down_revision = '40baa6923f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_table', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_table', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
