"""empty message

Revision ID: 504e7d97245b
Revises: 
Create Date: 2024-08-21 21:20:06.815499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504e7d97245b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('ssn', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('doctors_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_doctors_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors_table.id'], name=op.f('fk_appointments_table_doctor_id_doctors_table')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients_table.id'], name=op.f('fk_appointments_table_patient_id_patients_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors_table.id'], name=op.f('fk_doctors_notes_doctor_id_doctors_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_note_patient',
    sa.Column('doctor_note_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_note_id'], ['doctors_notes.id'], name=op.f('fk_doctor_note_patient_doctor_note_id_doctors_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients_table.id'], name=op.f('fk_doctor_note_patient_patient_id_patients_table')),
    sa.PrimaryKeyConstraint('doctor_note_id', 'patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_note_patient')
    op.drop_table('doctors_notes')
    op.drop_table('appointments_table')
    op.drop_table('doctors_table')
    op.drop_table('users_table')
    op.drop_table('patients_table')
    # ### end Alembic commands ###
