"""initialized

Revision ID: 6d3bb5ef2f10
Revises: 5c2644b75262
Create Date: 2024-08-18 15:40:50.988771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3bb5ef2f10'
down_revision = '5c2644b75262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssn', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('year_joined', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year_joined')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('ssn')

    # ### end Alembic commands ###
